### ISSUE TITLE
creating401UniqueRecords Test Method Fails

### ISSUE THREAD

**Issue by tompatros** [mbotos/SmartFactory-for-Force.com#12]
I dropped SmartFactory into a fresh dev org this morning and noticed the creating401UniqueRecords() test method is failing with "too many script statements: 200001".

I tweaked the last createSObjectList parameter on line 54 in SmartFactory_Tests and determined that 323 records pass and 324 records fail. 

Let me know if you need more details or further testing. I forked the project with the intent of adding some default value parameters. This project has great potential for us - happy to help if you need anything.

**Comment by mbotos** [comment]
Since SmartFactory wasn't designed for bulk data creation, I've removed the bulk unit tests.
