### ISSUE TITLE
Custom validation rules fail SmartFactory_Test

### ISSUE THREAD

**Issue by Xtremefaith** [mbotos/SmartFactory-for-Force.com#22]
So I simply deployed smart factory and all classes to sandbox, then ran the SmartFactory_Test.cls and got 1/4 passing results. I understand that I have custom fields on objects and validation rules that might be in place on my organization but I thought the point of SmartFactory was that it figured that all out when it described the object.

Her's my results:

**createsSingleObjectWithSingleRequiredStringField()**
`System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Invalid entry for field Terms.: [Acc_Customer_Terms__c]
Stack Trace	Class.SmartFactory_Test.createsSingleObjectWithSingleRequiredStringField: line 25, column 1`

**createsObjectWithoutCascadeDoesNotSetLookupField()**
`System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You must provide an Account Name for this Contact.: [AccountId]
Stack Trace	Class.SmartFactory_Test.createsObjectWithoutCascadeDoesNotSetLookupField: line 39, column 1`

**createsObjectWithCascadeSetsLookupField()**
`System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Campaign_RR_Contact__c]: [Campaign_RR_Contact__c]
Stack Trace	Class.SmartFactory.setFieldValue: line 213, column 1
Class.SmartFactory.createSObject: line 69, column 1
Class.SmartFactory.createSObject: line 76, column 1
Class.SmartFactory_Test.createsObjectWithCascadeSetsLookupField: line 31, column 1`

Please let me know if there is something else I need to do for the setup to work properly. I googled around and don't see anyone else having this problem so wondering if its just me. Thanks in advance for any help you can provide.

**Comment by mbotos** [comment]
Thanks for trying SmartFactory. It should automatically detect and fill fields where you've checked the "Required" checkbox; which object has the Campaign_RR_Contact__c field?

Validation rules aren't handled by SmartFactory, so you'll need to set those fields manually like this:
```java
Account account = (Account)SmartFactory.createSObject('Account');
account.Acc_Customer_Terms__c = 'Net 30';
insert account;
```

**Comment by Xtremefaith** [comment]
Is this something I would just modify my version of SmartFactory.cls with or that is something that I would have to do every time I create that object? I'll address the validation issues first to see if the snowballs my other issues. 

Really hoping to integrate this today, trying to structure our Unit Test patterns/framework because past week we've missed deployment deadlines simply because of 75% CC, getting mixed results from deployment vs "Run All Test"

**Comment by Xtremefaith** [comment]
Since this has got to be a common thing, what if you provided a way for setting up SmartFactory so that you only have to do this one time. For example in the `createSObject()` method, just before the return you added something like:

`SmartFactorySettings.validationRules(obj);`

Then in separate file that the developer can manage there could be some setup, perhaps like:

    /* Update with personal preferences */
	public class SmartFactorySettings {

		/* Add Validation Rules by account */
		public static validationRules(SObject obj){
			if(objectType == 'Account') obj.put('Acc_Customer_Terms__c', 'Net 30');    
		}
	}

You would probably know better than me, but a thought. Cause honestly I wouldn't use this if I had to insert those every time I created an object myself, that defeats the whole purpose of why I would use it.

**Comment by mbotos** [comment]
We've talked about adding a feature to set fields to certain values, but it's a big enough change that no one's been able to tackle it yet.

My recommendation is to wrap SmartFactory with your own class like this:
```java
public class TestObjectFactory {
  public static Account createAccount() {
    Account account = (Account)SmartFactory.createSObject('Account');
    account.Acc_Customer_Terms__c = 'Net 30';
    return account;
  }
}
```
You could then call that reusable method from your tests and just modify SmartFactory_Test.

**Comment by Xtremefaith** [comment]
That makes sense. I've begun this approach now and so far its going well. Although I'm wondering to do this with cascaded objects. For example when I build a Contact like so:

    Contact contact = (Contact) Forge.createSObject('Contact');

No problem, contact is constructed. But when a contact needs to be built with an account (which we have as a validation rule), 1) I have no way of passing a pre-constructed accountId and 2) when I set to cascade it creates a new user as well which then has a validation rule to ensure the user has an email within our domain. 

    Contact contact = (Contact) Forge.createSObject('Contact',true);

I would know how to check for our domain and manually override the Email field (replacing the default 'Email=test1@test.com' value), but not sure how to do that when dealing with your cascading approach.

At the moment I have this method in my wrapper class:

    public static SObject createSObject(String objectType, boolean cascade, Integer counter) {
		SObject obj = SmartFactory.createSObject(objectType,cascade,counter);
		validate(obj);
		return obj;
	}

And my validation method looks like this:

    private static SObject validate(SObject obj){
		/* Accounts */
		if(obj.getSObjectType() == Account.sObjectType){
			obj.put('Acc_Customer_Terms__c','Net 30');
		}
		/* Contacts */
		if(obj.getSObjectType() == Contact.sObjectType){
			if()
			obj.put('Acc_Customer_Terms__c','Net 30');
		}
		
		return obj;
	}

Thanks for getting me going with this, starting to feel like this approach could really work for us, once I get these things worked out.

**Comment by Xtremefaith** [comment]
Unless you have a better solution in mind the way I had to fix this was in line 211 when it attempts to create a reference SObject I have to change it to my namespace so that it passes through my validation rules for that SObject like so:

    SObject reference = Forge.createSObject(referenceObjectType);

Once I made that chance my `validate()` method in my Forge wrapper class took care of it. 

I think this project is foundational to any APEX developer, and since it seems to be a popular tool referenced by the community it would be worth improving. If there is anything I could do to help with development I wouldn't mind contributing.

**Comment by Xtremefaith** [comment]
So although I fixed the email validation issue it appears the new issue is how do I prevent cascading on an object like `Contact` from attempting to add a new User?

Reason being, I will now hit a user license issue:

    18:09:13.734 (734847514)|FATAL_ERROR|System.DmlException: Insert failed. First exception on row 0; first error: LICENSE_LIMIT_EXCEEDED, License Limit Exceeded: []

**Comment by mbotos** [comment]
Overriding within the cascade is a bit beyond the scope of SmartFactory. Glad you've been able to make progress with your modifications.

To avoid User license limits, you could exclude your custom User lookup fields on Contact by adding them to the SmartFactory.ExcludedFields map.

**Comment by Xtremefaith** [comment]
Thanks for pointing out SmartFactory.ExcludedFields map, good to know. In general I think I get how to add things for exclusion, but in this instance I'm not sure what the issue is. Again I assume this is common scenario, that when cascading 'Contact' object its going to reference a user for the OwnerId or actually in this case is it the `User` Childsobject. Either case how do you prevent it from creating the child object as new, but still provide a value.

Also, is there any sort of caching within SmartFactory. I just noticed when I used SmartFactory within a loop to bulk load accounts it took a really long time, and developer console shoes the APEX_CODE took 2,656.22 milliseconds that time, when in prior adding `New Account()` manually was considerably less. I'm guessing because every `(Account) SmartFactory.createSObject('Account')` call in the loop is RE-describing the object every time.

**Comment by Xtremefaith** [comment]
Also I found the `createSObjectList()` method and used that as well. Now I'm getting 9,579.18 ms (I thought it would have been less doing it that way compared to previously using a i for loop of 200:

    for (Integer i=0;i<200;i++) {
        Account account = (Account) SmartFactory.createSObject('Account');
    }

**Comment by mbotos** [comment]
The standard User lookups like OwnerId should be excluded by default. For custom field lookups, creating the cascading object is a global on/pff.

Interesting to see the time comparisons. SmartFactory caches some of the describe metadata, but not the generated objects. For a faster test, you could create a single object with SmartFactory and then clone it to fill your list.

**Comment by Xtremefaith** [comment]
So your tip about cloning helped a lot! Night and day difference in the numbers once I created an object and then in loop cloned that object as opposed to using `createSObjectList()`. **CPU time went from 7k+ down to 118 out of 10,000** (*governing limit*). Also the time went from a total of **19,472.6 MS to 1,298.75 MS** for the entire test class. These results would make me question if anyone should use `createSObjectList()` in its current state

As for the contact cascading issue. you are saying that the OwnerId which represent the user should ALREADY be excluded so there must be another reason its attempting to cascade it? If so does that mean I just need to find the responsible and exclude it like so?

    'Contact' => new set<String>{'Custom_User_Field__c'}
