### ISSUE TITLE
Cross referencing objects causes infinite loop

### ISSUE THREAD

**Issue by aluukka** [mbotos/SmartFactory-for-Force.com#24]
@mbotos I have a junction object between a custom object Location__c and Contact, called Location_Contact__c. For testing purposes I need to start from the Contact, which in turn creates the custom Location_Contact, which tries to create another Contact leads to in an infinite loop. 

Do you have advice on how to prevent the infinite looping

**Comment by mbotos** [comment]
SmartFactory doesn't have specific options for cross-references. In general, it'd be best to start with  SmartFactory creating your junction object. To prevent infinite looping, you can add additional cross-reference fields to the Excluded Fields map and set them manually as needed.
