### ISSUE TITLE
INVALID_CROSS_REFERENCE_KEY

### ISSUE THREAD

**Issue by mhuff24** [mbotos/SmartFactory-for-Force.com#25]
Hello,

I'm having an issue with the smart factory that I am hoping you can help me with. When I run the tests, two of them fail with the following messages:
***
1:
System.DmlException: Insert failed. First exception on row 0; first error: INVALID_CROSS_REFERENCE_KEY, Record Type ID: this ID value isn't valid for the user: 012000000000000AAA: [RecordTypeId]

Stack Trace
Class.SmartFactory.setFieldValue: line 216, column 1 Class.SmartFactory.createSObject: line 68, column 1 Class.SmartFactory.createSObject: line 75, column 1 Class.SmartFactory_Test.createsObjectWithCascadeSetsLookupField: line 28, column 1

2:
System.DmlException: Insert failed. First exception on row 0; first error: INVALID_CROSS_REFERENCE_KEY, Record Type ID: this ID value isn't valid for the user: 012000000000000AAA: [RecordTypeId]

Stack Trace
Class.SmartFactory_Test.createsSingleObjectWithSingleRequiredStringField: line 22, column 1
***
Why is this happening and what is the best way to fix it?

Thanks!
Michael

**Comment by mbotos** [comment]
Hi Michael,
SmartFactory uses the default Master Record Type ID. It looks like you don't have security permissions for it.

To fix it, you'll need to add that Record Type to your Profile.

**Comment by mhuff24** [comment]
Hi and thanks for the reply.  I currently have admin rights in this org so I should have the proper rights to see all the record types.  Could this problem be caused by something else?
