### ISSUE TITLE
isIncludedField method

### ISSUE THREAD

**Issue by mhuff24** [mbotos/SmartFactory-for-Force.com#26]
I am going through the code now and I am wondering when and how the **isIncludedField** method could ever return true? 

In that method, the **fields** variable is being set to **includedFields.get(obj.getSObjectType().getDescribe().getName())** but the **includedFields** map is never populated with data anywhere else in the code so wouldn't it always be false?  If so then what is the purpose of this method?

**Comment by mbotos** [comment]
I added an "Include or Exclude Fields" section to the Readme documentation.
