### ISSUE TITLE
isPersonAccountField method

### ISSUE THREAD

**Issue by mhuff24** [mbotos/SmartFactory-for-Force.com#27]
I am going through the code now and I have some questions about the **isPersonAccountField** method.

In that method, the **skipPersonAccountFields** variable is being set to **new Set<String> { 'Salutation' }** each time the method is called. Later in the return statement one of the true conditions are if person accounts are enabled and if the **skipPersonAccountFields** variable contains the name of the field being passed in.

My question is when would that ever be true? I dont see anywhere where the **skipPersonAccountFields** variable could be populated with the name if the field being passed in so what is the purpose of this code?

**Comment by mbotos** [comment]
I didn't write the PersonAccount handling, but it also depends on the Salesforce org settings.

To understand it, you could create two Salesforce dev orgs with and without PersonAccounts enabled. Then you can step through the code in the debugger in each.
