### ISSUE TITLE
Create Record For Specific Record Type

### ISSUE THREAD

**Issue by AAnantAgarwal** [mbotos/SmartFactory-for-Force.com#28]
I was trying to create a Record of Account with a specific Record Type. How can we achieve this? Is there any existing way or need to made some modifications in your code?

**Comment by mbotos** [comment]
Sure, you can set the Account Record Type before inserting it like this:
```
Account account = (Account)SmartFactory.createSObject('Account');
account.RecordTypeId = myRecordTypeId;
insert account;
```
